apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: dogood
  namespace: argocd
spec:
  description: doGood project
  sourceRepos:
    - 'https://github.com/<your-username>/dogood-gitops.git'
  destinations:
    - namespace: default
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'