apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - path: patch-replicas.yaml
  - path: patch-imagepullpolicy.yaml

images:
  - name: us-central1-docker.pkg.dev/dogood-488720/dogood-repo/dogood
    newTag: latest